# lichess api token
token = ""

# on/off flags
debug = false
center_pieces = false

# ui settings
tile_height = 7
tile_width = 4

# piece rendering options
# Pieces render as their full names by default, as shown in the preview image on the GitHub repository.
[pieces]

[pieces.king]
render_black = "♔"
render_white = "♚"

[pieces.queen]
render_black = "♕"
render_white = "♛"

[pieces.rook]
render_black = "♖"
render_white = "♜"

[pieces.bishop]
render_black = "♗"
render_white = "♝"

[pieces.knight]
render_black = "♘"
render_white = "♞"

[pieces.pawn]
render_black = "♙"
render_white = "p"
